# Generated by Django 3.1.1 on 2020-10-04 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20201004_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='flat_number',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='house_number',
            field=models.SmallIntegerField(default=88),
            preserve_default=False,
        ),
    ]
