# Generated by Django 3.1.1 on 2020-10-04 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gallery', '0004_auto_20201004_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='handicraft',
        ),
        migrations.CreateModel(
            name='OrderHandicraft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False)),
                ('handicraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.handicraft')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='order_handicraft',
            field=models.ManyToManyField(to='gallery.OrderHandicraft'),
        ),
    ]
