# Generated by Django 3.1.1 on 2020-10-06 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_order_ordered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_handicraft',
        ),
    ]
