# Generated by Django 3.1.1 on 2020-10-06 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_remove_order_order_handicraft'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderHandicraft',
        ),
    ]
