# Generated by Django 3.1.1 on 2020-10-06 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0009_delete_orderhandicraft'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderArt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('handicraft', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gallery.handicraft')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gallery.order')),
            ],
        ),
    ]
