# Generated by Django 3.1.1 on 2020-10-06 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0011_remove_orderart_handicraft'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderart',
            name='order',
        ),
    ]
