# Generated by Django 3.1.1 on 2020-10-06 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0013_auto_20201006_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='handicrafts',
            field=models.ManyToManyField(to='gallery.Handicraft'),
        ),
    ]
