# Generated by Django 3.1.1 on 2020-10-07 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0014_order_handicrafts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='handicrafts',
        ),
    ]
