# Generated by Django 3.1.1 on 2020-10-07 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0016_order_handicrafts'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='additional_info',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
